### PR TITLE
Rename Code of Conduct file

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by adrienbrunet** [comment]
Don't you like "coc"?
Are you afraid someone won't understand?
🚲

**Comment by ewjoachim** [comment]
No, it just was the only capitalized abbreviation among all the file names, did it only for consistency.

**Comment by adrienbrunet** [comment]
Hope we'll all sleep better tonight.

**Comment by ewjoachim** [comment]
Well I know I will.

If you want, next time, I'll merge it myself :)

**Comment by adrienbrunet** [comment]
No please: That way, I can assess how painstaking you are. 😈

**Comment by ewjoachim** [comment]
Oh, the answer to this one is simple. **very**.

**Pull request merged**
