### PR TITLE
Renamed post to change its url

### PR DESCRIPTION
**Pull request by ewjoachim**
Manifesto current URL is `http://beautifuldjango.com/manifesto/2016/09/11/welcome-to-jekyll.html`

BTW, I love the idea of your book, and I'll be thrilled to have a opportunity to contribute.

### CODE REVIEW

**Comment by adrienbrunet** [comment]
hold on tiger. I haven't ping you... yet.... =) The manifesto isn't out already (officially), I need more work on it. And a bit of review from native speakers.

**Comment by ewjoachim** [comment]
well it's out there, so... ^^

**Comment by adrienbrunet** [comment]
hush....! =)

**Comment by ewjoachim** [comment]
:hushed:

**Pull request merged**
